import { describe, it, expect } from "vitest";
import { makeFunctionReference } from "convex/server";
import { api } from "./_generated/api";
import { setup, signedIn } from "./test.setup";
import type { Id } from "./_generated/dataModel";

type T = ReturnType<typeof setup>;

// convex/_generated/api.d.ts is regenerated by `npx convex dev` (not run in this lane), so
// reference the function by name; swap for `api.examples.load` once the api types include it.
const load = makeFunctionReference<
  "mutation",
  Record<string, never>,
  { loaded: boolean; purchaseIds: Id<"purchases">[] }
>("examples:load");

async function worldOf(t: T, userId: Id<"users">) {
  return t.run(async (ctx) => {
    const purchases = await ctx.db
      .query("purchases")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
    const items = await ctx.db
      .query("items")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
    const claims = await ctx.db
      .query("claims")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();
    const policies = (await ctx.db.query("policies").collect()).filter((p) => p.userId === userId);
    const priceChecks = (await ctx.db.query("priceChecks").collect()).filter((p) => p.userId === userId);
    const events = (await ctx.db.query("ledgerEvents").collect()).filter((e) => e.userId === userId);
    return { purchases, items, claims, policies, priceChecks, events };
  });
}

describe("examples.load", () => {
  it("seeds two example purchases owned by the caller", async () => {
    const t = setup();
    const { as, userId } = await signedIn(t);
    const before = Date.now();
    const res = await as.mutation(load, {});
    expect(res.loaded).toBe(true);
    expect(res.purchaseIds).toHaveLength(2);

    const w = await worldOf(t, userId);
    expect(w.purchases).toHaveLength(2);
    for (const p of w.purchases) {
      expect(p.userId).toBe(userId);
      expect(p.isExample).toBe(true);
      expect(p.status).toBe("active");
      expect(p.merchant).toBe("Northwind Outfitters");
      expect(p.purchasedAt).toBeLessThan(before);
    }
    expect(w.items).toHaveLength(3);
    expect(w.claims).toHaveLength(3);
    for (const c of w.claims) {
      expect(c.userId).toBe(userId);
      expect(c.isExample).toBe(true);
      expect(Number.isInteger(c.expectedCents)).toBe(true);
    }
    for (const i of w.items) expect(Number.isInteger(i.unitCents)).toBe(true);
  });

  it("returns story: sweater credited, scarf open for 4000 against a confirmed .example policy", async () => {
    const t = setup();
    const { as, userId } = await signedIn(t);
    await as.mutation(load, {});
    const w = await worldOf(t, userId);

    const sweater = w.items.find((i) => i.unitCents === 8000)!;
    const scarf = w.items.find((i) => i.unitCents === 4000)!;
    expect(sweater.returned).toBe(true);
    expect(scarf.returned).toBe(true);

    const sweaterClaim = w.claims.find((c) => c.itemId === sweater._id)!;
    expect(sweaterClaim.status).toBe("confirmed");
    expect(w.events.filter((e) => e.claimId === sweaterClaim._id).map((e) => e.cents)).toEqual([8000]);

    const scarfClaim = w.claims.find((c) => c.itemId === scarf._id)!;
    expect(scarfClaim.type).toBe("return_credit");
    expect(scarfClaim.expectedCents).toBe(4000);
    expect(scarfClaim.status).toBe("detected");
    expect(w.events.filter((e) => e.claimId === scarfClaim._id)).toHaveLength(0);

    const policy = w.policies.find((p) => p._id === scarfClaim.policyId)!;
    expect(policy.kind).toBe("returns");
    expect(policy.confirmedByUser).toBe(true);
    expect(policy.isExample).toBe(true);
    expect(policy.contactEmail).toMatch(/\.example$/);
    for (const p of w.policies) expect(p.contactEmail).toMatch(/@[a-z.]+\.example$/);

    const got = await as.query(api.claims.get, { claimId: scarfClaim._id });
    expect(got.balance.unresolved).toBe(4000);
  });

  it("price story: 12000 bought, 9500 observed, 2500 claim with a future window", async () => {
    const t = setup();
    const { as, userId } = await signedIn(t);
    await as.mutation(load, {});
    const w = await worldOf(t, userId);

    const jacket = w.items.find((i) => i.unitCents === 12000)!;
    expect(jacket.returned).toBe(false);
    const claim = w.claims.find((c) => c.type === "price_adjustment")!;
    expect(claim.itemId).toBe(jacket._id);
    expect(claim.expectedCents).toBe(2500);
    expect(claim.windowEndsAt!).toBeGreaterThan(Date.now());

    const check = w.priceChecks.find((c) => c._id === claim.openedFromPriceCheckId)!;
    expect(check.itemId).toBe(jacket._id);
    expect(check.observedCents).toBe(9500);
    expect(check.sourceUrl).toContain("northwind.example");

    const policy = w.policies.find((p) => p._id === claim.policyId)!;
    expect(policy.kind).toBe("price_adjustment");
    expect(policy.windowDays).toBe(14);
  });

  it("is idempotent per user", async () => {
    const t = setup();
    const { as, userId } = await signedIn(t);
    const first = await as.mutation(load, {});
    const a = await worldOf(t, userId);
    const second = await as.mutation(load, {});
    const b = await worldOf(t, userId);

    expect(second.loaded).toBe(false);
    expect([...second.purchaseIds].sort()).toEqual([...first.purchaseIds].sort());
    expect(b.purchases).toHaveLength(a.purchases.length);
    expect(b.items).toHaveLength(a.items.length);
    expect(b.claims).toHaveLength(a.claims.length);
    expect(b.policies).toHaveLength(a.policies.length);
    expect(b.priceChecks).toHaveLength(a.priceChecks.length);
    expect(b.events).toHaveLength(a.events.length);
  });

  it("gives a second user their own full copy", async () => {
    const t = setup();
    const one = await signedIn(t, "One");
    const two = await signedIn(t, "Two");
    await one.as.mutation(load, {});
    const res = await two.as.mutation(load, {});
    expect(res.loaded).toBe(true);

    const w1 = await worldOf(t, one.userId);
    const w2 = await worldOf(t, two.userId);
    expect(w2.purchases).toHaveLength(2);
    expect(w2.claims).toHaveLength(3);
    expect(w2.events).toHaveLength(1);
    expect(w2.claims.filter((c) => c.status === "confirmed")).toHaveLength(1);
    expect(w1.purchases).toHaveLength(2);
    const ids1 = new Set(w1.purchases.map((p) => p._id));
    for (const p of w2.purchases) expect(ids1.has(p._id)).toBe(false);
    const tokens = [...w1.claims, ...w2.claims].map((c) => c.token);
    expect(new Set(tokens).size).toBe(tokens.length);
  });

  it("rejects unauthenticated callers and inserts nothing", async () => {
    const t = setup();
    await expect(t.mutation(load, {})).rejects.toThrow(/Not signed in/);
    const count = await t.run(async (ctx) => (await ctx.db.query("purchases").collect()).length);
    expect(count).toBe(0);
  });
});
