/**
 * Air-travel fact keys (M22, wave 2): R02 airline fare refund (docs/rules/R02-airline-refund.md §5) and R04 baggage
 * (docs/rules/R04-baggage.md §5). Keys are never renamed (stored rows and evaluations reference them).
 *
 * Mapping from the specs' typed fact tables (and the fixture names in docs/rules/fixtures/R02.json, R04.json) to the
 * closed fact-value kinds (contract §2.5):
 *   - a spec `enum` is a `code` key with its closed list, WITHOUT the spec's `unknown` member: "I don't know" is the
 *     fact layer's own `user_unknown` answer (DA-A-1), never a code;
 *   - `datetime` → `instant`; `date` → `local_date`; `boolean` → `bool`; `integer` → `count` (or `minutes`);
 *   - an `object` fact is split into one key per member: `original_airports` → `air.original_origin_airport` +
 *     `air.original_destination_airport` (and the changed pair); R04's `exemption_facts` → the three
 *     `air.exemption_*` booleans (+ `air.exemption_documented_by_carrier`, 260.5(f)(2));
 *   - a list fact is either a total or one `line:<n>` subject per entry: R02's `ancillary_fees_paid` (money[]) is the
 *     total `air.ancillary_fees_total` (a confirmed 0 records "no ancillary fees" — missing is not zero, R02 §16.8);
 *     R04's `expense_lines` and `property_items` are `line:<n>` subjects carrying `air.expense_*` / `air.property_*`;
 *   - R02's partly-flown itinerary (fixture `itinerary_legs`) is `air.partly_flown` (spec §8, assumption A4).
 *
 * R04 bag facts may sit on the transaction or on the bag's `incident:<id>` subject (one incident per bag), so a trip
 * with two bags keeps two sets. Itinerary facts (scope, segment length, large aircraft) are transaction-level.
 *
 * DA-A-18 (contract §3.2): a voucher/credit the user affirmatively accepted is recorded as `air.consumer_response` =
 * `accepted_compensation` — the key R02 already reads for P-260.7 "affirmatively agrees" — see
 * `AIR_VOUCHER_ACCEPTANCE`. (The contract's name `air.alternative.accepted` does not fit the catalogue's
 * `<domain>.<snake>` grammar, and a second key could contradict this one; raised with the lead.)
 */
import type { FactSpec } from "./catalog";
import { US_ZONES } from "../deadlines/usZones";

const AIR = ["air_travel"] as const;
const TXN = ["transaction"] as const;
/** Bag-level facts: on the transaction, or on the bag's incident (one incident per bag). */
const BAG = ["transaction", "incident"] as const;
const LINE = ["line"] as const;

const TICKET_DOCS = ["e_ticket", "order_confirmation", "receipt"] as const;
const CHANGE_DOCS = ["itinerary_change_notice", "cancellation_notice", "delay_notice"] as const;
const PAYMENT_DOCS = ["card_statement", "receipt"] as const;
const BAG_DOCS = ["baggage_report", "delivery_notice"] as const;

const CABINS = ["first", "business", "premium_economy", "economy"] as const;

export const AIR_FACT_SPECS = [
  // ---------------------------------------------------------------- R02 — ticket and itinerary
  {
    key: "air.itinerary_scope",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["domestic", "international", "non_us"],
    question: {
      prompt: "Does the trip stay inside the United States, or start or end abroad?",
      why: "US refund and baggage rules cover flights to, from or within the US, and the time limits differ for international trips.",
    },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    // D253(3)/D263: a covered flight is "a scheduled flight" (14 CFR 260.2). "unknown" records the user's "I don't know"
    // and is treated like a missing value (the result is capped with an assumption, never ruled out).
    key: "air.service_type",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["scheduled", "public_charter", "other_non_scheduled", "unknown"],
    question: {
      prompt: "Was this a regularly scheduled flight, or a charter or other non-scheduled flight?",
      why: "The airline refund rule covers scheduled flights; a charter has different rules.",
    },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.operating_carrier",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airline operated the flight?", why: "The airline that owes the refund is named on the request." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.marketing_carrier",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airline sold the flight under its own flight number?", why: "Either the operating or the marketing airline can be the one responsible." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.merchant_of_record",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["carrier", "ticket_agent"],
    question: {
      prompt: "Whose name is on the card or bank statement line for the ticket: the airline, or a travel agency or booking site?",
      why: "An airline that took the payment must refund automatically; a travel agency refunds when you ask it to.",
    },
    evidenceHint: PAYMENT_DOCS,
    userAssertable: true,
  },
  {
    key: "air.ticket_refundability",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["nonrefundable", "refundable"],
    question: { prompt: "Was the ticket nonrefundable?", why: "Recoup's check covers nonrefundable tickets; refundable fares have their own terms." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.event_type",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["cancellation", "schedule_change", "operational_delay", "downgrade", "airport_change", "added_connection", "renumbered_only"],
    question: {
      prompt: "What happened to the flight: cancelled, rescheduled, delayed on the day, downgraded, moved to another airport, given an extra stop, or only renumbered?",
      why: "Each kind of change is measured differently under the DOT refund rule.",
    },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.ticket_number",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "identifier",
    identifierScheme: "eticket",
    question: { prompt: "What is the 13-digit ticket number?", why: "The airline uses it to find the ticket and its refund." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.original_flight_number",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "identifier",
    identifierScheme: "flight_number",
    question: { prompt: "What was the original flight number?", why: "It identifies the flight that was cancelled or changed." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_flight_number",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "identifier",
    identifierScheme: "flight_number",
    question: { prompt: "What is the new flight number?", why: "A flight that was only renumbered is handled differently." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.original_sched_departure_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When was the flight originally scheduled to depart?", why: "A departure moved three or more hours earlier (six abroad) is a significant change." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.original_sched_arrival_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When was the flight originally scheduled to arrive?", why: "An arrival three or more hours later (six abroad) is a significant change." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_sched_departure_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When is the changed flight scheduled to depart?", why: "Recoup compares the new schedule with the original one." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_sched_arrival_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When is the changed flight scheduled to arrive?", why: "Recoup compares the new schedule with the original one." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.actual_arrival_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When did the flight actually arrive?", why: "The law counts when you arrive; the regulation counts the schedule. When they disagree, a person reviews it." },
    evidenceHint: ["delay_notice"],
    userAssertable: true,
  },
  {
    key: "air.original_origin_airport",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airport was the trip originally departing from?", why: "A change of airport is a significant change." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.original_destination_airport",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airport was the trip originally arriving at?", why: "A change of airport is a significant change." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_origin_airport",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airport does the changed trip depart from?", why: "A change of airport is a significant change." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_destination_airport",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airport does the changed trip arrive at?", why: "A change of airport is a significant change." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.original_connections",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "count",
    max: 20,
    question: { prompt: "How many connections did the original itinerary have?", why: "An itinerary with more connections than the original is a significant change." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_connections",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "count",
    max: 20,
    question: { prompt: "How many connections does the changed itinerary have?", why: "An itinerary with more connections than the original is a significant change." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.original_cabin",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: CABINS,
    question: { prompt: "Which cabin did you book?", why: "A downgrade to a lower class of service is a significant change." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.changed_cabin",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: CABINS,
    question: { prompt: "Which cabin is the changed flight in?", why: "A downgrade to a lower class of service is a significant change." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.passenger_disability_relevant",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "bool",
    question: {
      prompt: "Does a disability make the new connecting airport or the substitute aircraft a problem for you?",
      why: "Two extra refund grounds apply to travellers with a disability; a person reviews them with you.",
      sensitive: true,
    },
    userAssertable: true,
  },
  {
    key: "air.offer_type",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["none", "rebooking", "voucher_or_credit", "both"],
    question: {
      prompt: "What did the airline offer you instead: nothing, another flight, a voucher or credit, or both?",
      why: "What was offered decides when a refund request is treated as made.",
    },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.consumer_response",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["rejected", "accepted_rebooking", "accepted_compensation", "no_response"],
    question: {
      prompt: "Did you accept the new schedule, reject it, or not respond?",
      why: "If you do not respond and do not take the changed flight, DOT rules treat that as a refund request once the flight departs. Only a voucher you actively accepted replaces the refund.",
    },
    evidenceHint: ["merchant_correspondence", "itinerary_change_notice"],
    userAssertable: true,
  },
  {
    key: "air.consumer_response_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When did you reject the airline's offer?", why: "The airline's refund deadline counts from that moment." },
    evidenceHint: ["merchant_correspondence"],
    userAssertable: true,
  },
  {
    key: "air.flew_changed_or_alternative",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "bool",
    question: { prompt: "Did you fly the changed flight or the replacement flight?", why: "Flying it means the refund rule no longer applies." },
    evidenceHint: ["e_ticket"],
    userAssertable: true,
  },
  {
    key: "air.changed_or_alternative_departs_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When does (or did) the changed or replacement flight depart?", why: "If you do not respond, the refund request counts from its departure." },
    evidenceHint: CHANGE_DOCS,
    userAssertable: true,
  },
  {
    key: "air.cancellation_notice_at",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "instant",
    question: { prompt: "When did the airline tell you the flight was cancelled?", why: "With nothing offered in its place, the refund deadline counts from that notice." },
    evidenceHint: ["cancellation_notice"],
    userAssertable: true,
  },
  {
    key: "air.payment_method_class",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: ["credit_card", "debit_card", "cash", "check", "miles", "other"],
    question: { prompt: "How did you pay for the ticket?", why: "Credit-card refunds are due within 7 business days; other payments within 20 days." },
    evidenceHint: PAYMENT_DOCS,
    userAssertable: true,
  },
  {
    key: "air.fare_paid",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: { prompt: "What fare did you pay, before taxes?", why: "The refund is the full fare plus taxes and fees." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.taxes_paid",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: { prompt: "How much did you pay in taxes and government fees on the ticket?", why: "Taxes are refunded with the fare." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.ancillary_fees_total",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: {
      prompt: "How much did you pay in extra fees for the cancelled or changed flight (seats and similar, not checked-bag fees)? Enter 0 if none.",
      why: "Those fees are refunded with the fare; a checked-bag fee is refunded separately. Recoup never assumes there were none.",
    },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.already_refunded",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: {
      prompt: "How much had the airline already refunded before you started this case? Enter 0 if nothing.",
      why: "Only what is still owed is requested. Money that arrives after the case starts is recorded on the case instead, so it is never subtracted twice.",
    },
    evidenceHint: ["card_statement", "refund_notice"],
    userAssertable: true,
  },
  {
    // D221: the ticket's total as paid (fare + taxes + fees), e.g. from manual entry (`transactions.createManual`).
    // Contract §3.4's per-transaction paid cap for air. Read by no R02/R04 v1 logic.
    key: "air.total_paid",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: { prompt: "What did you pay in total for this ticket, including taxes and fees?", why: "Recovered money on this trip is never shown as more than you paid." },
    evidenceHint: ["receipt", "card_statement"],
    userAssertable: true,
  },
  {
    key: "air.partly_flown",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "bool",
    question: { prompt: "Did you already fly part of this ticket (for example the outbound flight)?", why: "The rule does not say how to split a partly used ticket, so a person checks the amount." },
    evidenceHint: ["e_ticket"],
    userAssertable: true,
  },
  {
    key: "air.home_time_zone",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "code",
    codes: US_ZONES.map((z) => z.id),
    question: {
      prompt: "Which time zone do you live in?",
      why: "The airline's refund deadline counts calendar days where you are; without it Recoup uses the earliest-ending US time zone.",
    },
    userAssertable: true,
  },
  // ---------------------------------------------------------------- R04 — bags
  {
    key: "air.longest_us_foreign_nonstop_segment_minutes",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "minutes",
    max: 1440,
    question: {
      prompt: "How long was the longest nonstop flight between the US and another country on this trip?",
      why: "A bag counts as significantly delayed after 15 hours when that flight is 12 hours or shorter, and after 30 hours when it is longer.",
    },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.operating_carrier_last_segment",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: { prompt: "Which airline operated the last flight of the trip?", why: "That airline takes the baggage report and refunds the bag fee." },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.bag_fee_merchant_of_record",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "code",
    codes: ["carrier", "ticket_agent"],
    question: { prompt: "Who charged the bag fee: the airline, or a travel agency or booking site?", why: "Either way the refund is requested from the airline." },
    evidenceHint: PAYMENT_DOCS,
    userAssertable: true,
  },
  {
    key: "air.bag_fee_paid",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "money",
    question: { prompt: "What fee did you pay to check this bag? Enter 0 if it was free.", why: "The airline must refund at least that fee." },
    evidenceHint: ["receipt", "card_statement"],
    userAssertable: true,
  },
  {
    key: "air.bag_tag_number",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "identifier",
    identifierScheme: "bag_tag",
    question: { prompt: "What is the bag tag number?", why: "It identifies the bag on the report and the claim." },
    evidenceHint: BAG_DOCS,
    userAssertable: true,
  },
  {
    key: "air.deplane_opportunity_at",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "instant",
    question: { prompt: "When could you get off the plane at your final destination?", why: "The bag's delay is counted from that moment." },
    evidenceHint: ["e_ticket", "delay_notice"],
    userAssertable: true,
  },
  {
    key: "air.bag_delivered_or_picked_up_at",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "instant",
    question: { prompt: "When was the bag delivered to you or picked up?", why: "The delay ends at delivery or pickup." },
    evidenceHint: ["delivery_notice"],
    userAssertable: true,
  },
  {
    key: "air.bag_status",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "code",
    codes: ["delivered", "delayed_undelivered", "declared_lost", "damaged", "pilfered"],
    question: { prompt: "Where is the bag now: delivered, still missing, declared lost by the airline, or damaged?", why: "A lost bag needs no delay calculation; a damaged or lost bag is a property claim." },
    evidenceHint: BAG_DOCS,
    userAssertable: true,
  },
  {
    key: "air.mbr_filed",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "bool",
    question: {
      prompt: "Did you file a missing-bag report (Mishandled Baggage Report) with the airline?",
      why: "The bag-fee refund is owed only after that report is filed; add its reference number if you have it.",
    },
    evidenceHint: ["baggage_report"],
    userAssertable: true,
  },
  {
    key: "air.mbr_reference",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "text",
    question: { prompt: "What is the baggage report's reference number?", why: "It proves the report was filed." },
    evidenceHint: ["baggage_report"],
    userAssertable: true,
  },
  {
    key: "air.mbr_filed_at",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "instant",
    question: { prompt: "When did you file the baggage report?", why: "It shows the report exists and when the refund duty began." },
    evidenceHint: ["baggage_report"],
    userAssertable: true,
  },
  {
    key: "air.exemption_failed_recheck",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "bool",
    question: {
      prompt: "Did the airline record that you did not pick up and recheck the bag at your first US entry point (customs)?",
      why: "That is one of three reasons the airline can refuse the bag-fee refund.",
    },
    evidenceHint: ["baggage_report", "merchant_correspondence"],
    userAssertable: true,
  },
  {
    key: "air.exemption_failed_pickup",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "bool",
    question: {
      prompt: "Did the bag arrive on time at your ticketed destination while you ended the trip elsewhere or did not collect it?",
      why: "The airline may refuse the refund for that only if it documented it.",
    },
    evidenceHint: ["merchant_correspondence"],
    userAssertable: true,
  },
  {
    key: "air.exemption_voluntary_separation",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "bool",
    question: {
      prompt: "Did you agree to travel without the bag on the same flight (for example a late check-in or standby)?",
      why: "That can remove the refund for a delayed bag, but not for a lost one.",
    },
    evidenceHint: ["merchant_correspondence"],
    userAssertable: true,
  },
  {
    key: "air.exemption_documented_by_carrier",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "bool",
    question: {
      prompt: "Has the airline documented that the bag waited at the destination because of you?",
      why: "Without the airline's documentation that reason cannot be used to refuse the refund.",
    },
    evidenceHint: ["merchant_correspondence"],
    userAssertable: true,
  },
  {
    key: "air.large_aircraft_segment_on_ticket",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "bool",
    question: {
      prompt: "Was any flight on the ticket on a plane with more than 60 seats?",
      why: "The federal minimum on the airline's liability limit applies only then.",
    },
    evidenceHint: TICKET_DOCS,
    userAssertable: true,
  },
  {
    key: "air.incident_date",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "local_date",
    question: { prompt: "On what date did you arrive without the bag (local date at the destination)?", why: "The liability limit in force on that date applies." },
    evidenceHint: BAG_DOCS,
    userAssertable: true,
  },
  {
    key: "air.carrier_liability_limit",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: {
      prompt: "What liability limit does the airline's contract of carriage state?",
      why: "It is the most the airline must pay for all your baggage losses; it is a limit, not a payout.",
    },
    evidenceHint: ["policy_page"],
    userAssertable: true,
  },
  {
    key: "air.carrier_claim_deadline",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: {
      prompt: "What deadline does the airline's contract of carriage give for baggage claims?",
      why: "Federal rules set none; the airline's own contract does, and Recoup has not captured it yet.",
    },
    evidenceHint: ["policy_page"],
    userAssertable: true,
  },
  {
    key: "air.carrier_exclusions",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "text",
    question: {
      prompt: "Which items does the airline's contract of carriage exclude from baggage claims?",
      why: "On domestic trips an airline need not pay for items its contract excludes.",
    },
    evidenceHint: ["policy_page"],
    userAssertable: true,
  },
  {
    // D236 (M27 ruling (13)): a reimbursement already received for this trip's baggage losses that is NOT recorded
    // against specific expense lines (e.g. an airline's interim lump sum). R04 v1 then asks which lines it covered.
    key: "air.reimbursement_received",
    domain: "air",
    categories: AIR,
    subject: TXN,
    value: "money",
    question: {
      prompt: "Has the airline, a card benefit or an insurer already paid you something for this bag that is not tied to specific receipts? How much?",
      why: "A payment that covered some of your expenses must not be claimed again; tell Recoup which expenses it covered.",
    },
    evidenceHint: ["refund_notice", "card_statement"],
    userAssertable: true,
  },
  {
    key: "air.user_claimed_total",
    domain: "air",
    categories: AIR,
    subject: BAG,
    value: "money",
    question: { prompt: "What total are you claiming?", why: "Shown for reference only; Recoup's estimate counts documented receipts." },
    userAssertable: true,
  },
  // ---------------------------------------------------------------- R04 — expense lines and property items (line:<n>)
  {
    key: "air.expense_amount",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "money",
    question: { prompt: "How much did this expense cost?", why: "Each documented expense counts toward the estimate." },
    evidenceHint: ["expense_receipt"],
    userAssertable: true,
  },
  {
    key: "air.expense_date",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "local_date",
    question: { prompt: "On what date did you buy it?", why: "Expenses count while the bag was delayed." },
    evidenceHint: ["expense_receipt"],
    userAssertable: true,
  },
  {
    key: "air.expense_description",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "text",
    question: { prompt: "What was the expense for?", why: "The airline decides what is reasonable; a clear description helps." },
    evidenceHint: ["expense_receipt"],
    userAssertable: true,
  },
  {
    key: "air.expense_receipt",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "text",
    question: { prompt: "Add the receipt for this expense.", why: "Only expenses with a receipt count toward the estimate." },
    evidenceHint: ["expense_receipt"],
    userAssertable: true,
  },
  {
    key: "air.expense_allocated_to",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "text",
    question: { prompt: "Has this expense already been claimed or paid somewhere else (for example a card benefit)?", why: "One expense can be claimed from only one place." },
    evidenceHint: ["card_statement"],
    userAssertable: true,
  },
  {
    key: "air.property_item",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "text",
    question: { prompt: "What item was lost or damaged?", why: "Each item is listed on the property claim." },
    evidenceHint: ["damage_photo", "receipt"],
    userAssertable: true,
  },
  {
    key: "air.property_claimed_value",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "money",
    question: { prompt: "What was the item worth?", why: "Shown as evidence; the airline applies depreciation and its limit." },
    evidenceHint: ["receipt"],
    userAssertable: true,
  },
  {
    key: "air.property_proof",
    domain: "air",
    categories: AIR,
    subject: LINE,
    value: "text",
    question: { prompt: "Add proof of this item (a receipt or a photo).", why: "Airlines ask for proof of what was in the bag." },
    evidenceHint: ["receipt", "damage_photo"],
    userAssertable: true,
  },
] as const satisfies readonly FactSpec[];

/**
 * DA-A-18: the fact `claims.recordNonCashResolution` (M20) writes, as a `user_confirmed` row on the transaction, when
 * the user records a voucher or credit they accepted for an R02 case. R02 v1 reads it as an affirmative acceptance of
 * compensation (P-260.7) → `not_eligible`.
 */
export const AIR_VOUCHER_ACCEPTANCE = Object.freeze({
  subjectKey: "txn",
  key: "air.consumer_response",
  value: Object.freeze({ kind: "code", code: "accepted_compensation" }),
} as const);
